FROM node:18-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV NAME value

COPY .server /usr/src/app
RUN npm install
RUN npm run build

FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app /usr/src/app
EXPOSE 80
CMD ["node", "dist/main.js"]