FROM node:18-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./client /usr/src/app

RUN npm install && npm cache clean --force
RUN npm run build
RUN ls -l /usr/src/app/dist

FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
RUN mkdir -p /etc/nginx/conf.d
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]